#!/usr/bin/env node

/**
 * Build script that pre-generates the HTML string for the Cloudflare Worker.
 *
 * It reads the MCP Apps SDK browser bundle and pako deflate from node_modules,
 * processes them (strip ESM exports, create App alias), and writes the final
 * HTML as an exported string to src/generated-html.js.
 *
 * Usage: node src/build-html.js
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildHtml, processAppBundle } from "./shared.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Read and process app-with-deps.js
const extAppsEntry = fileURLToPath(import.meta.resolve("@modelcontextprotocol/ext-apps/app-with-deps"));
const appWithDepsRaw = fs.readFileSync(extAppsEntry, "utf-8");
const appWithDepsJs = processAppBundle(appWithDepsRaw);

// Read pako deflate
const pakoEntry = fileURLToPath(import.meta.resolve("pako"));
const pakoDeflateJs = fs.readFileSync(
  path.join(path.dirname(pakoEntry), "..", "dist", "pako_deflate.min.js"),
  "utf-8"
);

// Read the shared XML reference (single source of truth for all prompts)
const xmlReference = fs.readFileSync(
  path.join(__dirname, "..", "..", "shared", "xml-reference.md"),
  "utf-8"
);

// Build the HTML and write it as an ES module export
const html = buildHtml(appWithDepsJs, pakoDeflateJs);
const outPath = path.join(__dirname, "generated-html.js");

fs.writeFileSync(outPath, `// Auto-generated by build-html.js — do not edit\nexport const html = ${JSON.stringify(html)};\nexport const xmlReference = ${JSON.stringify(xmlReference)};\n`);

console.log(`Generated ${outPath} (${(html.length / 1024).toFixed(1)} KB)`);
